# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Build
      run:
        mkdir --parents /home/runner/go/src/github.com/edotau/ &&
        cp -r ../goFish /home/runner/go/src/github.com/edotau/ &&
        cd /home/runner/go/src/github.com/edotau/goFish &&
        go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Test
      run: 
        mkdir --parents /home/runner/go/src/github.com/edotau/ &&
        cp -r ../goFish /home/runner/go/src/github.com/edotau/ &&
        cd /home/runner/go/src/github.com/edotau/goFish &&
        go test ./...
             
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: go fmt
        run: gofmt -s -w ./*/*.go
      - name: go fmt cmd
        run: gofmt -s -w ./cmd/*/*.go
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email "AutoFmtBot@fmtyacodeffs.com"
          git config --global user.name "AutoFmt Bot"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated go fmt"
          git push

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run coverage
        run: 
          mkdir --parents /home/runner/go/src/github.com/edotau/ &&
          cp -r ../goFish /home/runner/go/src/github.com/edotau/ &&
          cd /home/runner/go/src/github.com/edotau/goFish &&
          go test -coverprofile=coverage.txt -covermode=atomic ./...
          cat coverage.txt
