name: goFish-actions

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

    -name: Build
      run:
        mkdir -p ~/go/src/github.com/edotau/goFish &&
        cp -r ../goFish ~/go/src/github.com/edotau/ &&
        cd ~/go/src/github.com/edotau/goFish &&
        go test ./...

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: go fmt
        run: gofmt -s -w ./*/*.go
      - name: go fmt cmd
        run: gofmt -s -w ./*/*/*.go
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email "AutoFmtBot@fmtyacodeffs.com"
          git config --global user.name "AutoFmt Bot"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated go fmt"
          git push
